### ISSUE TITLE
Channel Combobox focusing address bar on Tab pressed 

### ISSUE THREAD

**Issue by ikidnapmyself** [sociozat/sociozat#22]
When I want to add new channels with my new post, I need to press Tab button on my keyboard but it opens Safari browser search bar with a container that almost disables the page. I need to press Esc to close it.

**To Reproduce**
1. Go to '/new' to create a new topic
2. Focus **Channels** combobox and find an unsaved channel name such as "test123"  
3. Only way to pick a new channel name is pressing Tab button and then you reproduced

**Expected behavior**
When I press tab to create a new one, it should allow me to add one more. But tab focuses address bar and it's bad for user behavior.

**Screenshots**
<img width="862" alt="image" src="https://user-images.githubusercontent.com/13779866/77554430-177f7e00-6ec7-11ea-9e21-beaa96bbcf3a.png">

**Mac:**
 - OS: MacOS Catalina 10.15.3
 - Browser Safari 
 - Version Version 13.0.5

**Comment by bencagri** [comment]
tab has been implemented.
